### ISSUE TITLE
UI - 'Command' details are truncated!

### ISSUE THREAD

**Issue by umairishaq** [wagoodman/dive#376] opened 2021-11-03 17:19 UTC
Running dive (as a container) with the following config:

* MacOS Big Sur (11.6)
* Docker Desktop 3.2.2
* Terminal 2.11(440)

The command used:

```
docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    wagoodman/dive:latest public.ecr.aws/c0q1x5l5/dask-quantlib
```

The UI does not show the complete command for a selected layer. The screenshot makes it visible.

<img width="1680" alt="Screen Shot 2021-11-03 at 1 13 06 PM" src="https://user-images.githubusercontent.com/1382679/140143903-78a8a481-1668-4f99-aadc-57dc0cc5d881.png">

**Comment by brian-finisher** [comment] 2021-11-18 20:24
This is especially annoying when I have an ARG set. For whatever reason, the ARG variable and value appears under the RUN command and that's *all* I can see - so every RUN line looks the same, unfortunately.

**Comment by brian-finisher** [comment] 2021-11-18 20:26
Actually, this appears to be a duplicate of #356

**Comment by huanyang01** [comment] 2022-06-06 05:58
Same issue when executing "dive postgres:11.5-alpine" and "dive postgres:11.6-alpine"

<img width="3586" alt="image" src="https://user-images.githubusercontent.com/12814316/172103826-88199f8d-1085-4a7d-8f41-9f9effda299d.png">

**Comment by wagoodman** [comment] 2023-07-06 15:38
Fixed in https://github.com/wagoodman/dive/pull/399

**Closed by wagoodman** 2023-07-06 15:38 UTC
