### ISSUE TITLE
Sluggish UI on images with a lot of files 

### ISSUE THREAD

**Issue by ChrisCinelli** [wagoodman/dive#119] opened 2018-11-30 18:32 UTC
With this image: https://hub.docker.com/r/butomo1989/docker-android-x86-9.0/ moving up and down on a layer can take a few seconds and spin the CPU up to 100%. 

If you push up and down a few times the wait time piles up. 

It seems the UI code that does some CPU intensive task for rendering the layer. I think there is a lot of room for optimizations.

I am not sure how this relates with #94

**Comment by wagoodman** [comment] 2018-12-01 17:06
There are definitely opportunities for optimizations. The easy route first was taken by building the view tree on the fly. `pprof` showed a lot of inefficiencies with view writes, which was fixed by drawing only the visible portion of the tree. I'll profile it again soon against this image to see if the sluggishness is due to this or something else.

**Comment by ccinelli** [comment] 2018-12-03 19:05
I look at the UI code (but not in depth) and profiled it. 

In `main.go` I added: 
```
import (
	"log"
	"net/http"
	_ "net/http/pprof"
...

func main() {
	...

	go func() {
		log.Println(http.ListenAndServe("localhost:6060", nil))
	}()

	...

	return tree
}
```

And then `go tool pprof http://localhost:6060/debug/pprof/profile` and I just start going up and down on the layers.

Then I created this graph with the `png` command:

![profile003](https://user-images.githubusercontent.com/38021940/49395337-09fb1f00-f6eb-11e8-9e55-0ff23940f0fa.png)

My takes:
It looks the code is coping over and over the filetree. That creates a lot of work for the CPU for creating and deleting (during garbage collection). The `filterRegex` also seems taking a lot of CPU.   

_Do you have to keep copying the filetree?_

I would probably had used different data structures:

1) The files on the layers of images will never change. Once you have the tar headers and the hash of the files you have everything you need. You can index stuff in maps by path, by hash, and whatever else you need so you can retrive things in O(1). This is by the way what I was talking about in #90 (2). As a side note, you could also cache the data about a layer or image hash on disk (on a `~/.dive/cache` forder maybe?) so next time somebody open `dive`, instead of opening the image you can just read from the cache without having to calculate hashes or even read the content of the layers... I would also consider using a sqlite db for that purpose. 
2) It can make sense to decoupled the data structure that stores the files on the layers and the UI state (forder expanded, etc).   
4) It is not necessary to redraw everything from scratch. Only the variations needs to change.

I can go more in details if you want me. 

It looks like you are already working on some refactoring so it is up to you.

**Comment by wagoodman** [comment] 2018-12-05 01:10
@ccinelli I appreciate the pprof output and comments. I additionally ran a memory profile this go around to see what is taking up space and found a few optimizations. 

Up front I decided to take the easy way first with implementation, only optimizing when it became necessary --it has now become necessary for large images. It looks like, in general, we are now looking at a classic time-v-space tradeoff game: do we want to store more or have the user wait for it to be computed? 

- based on the pprof output I focused on data copying first. The largest culprit of this was with tree "stacking" and comparisons. "Stacking" refers to taking multiple file trees and combining them (which requires copying entire trees), and comparisons were implemented by copying the original tree to ensure the comparison was being done against the un-mutated data.
- Removing any `viper.Get*` calls in places where it is called in a loop was apparently very helpful in saving memory (surprisingly)
- Reducing the hash chunk size made layer processing faster
- Consolidating the tar header info down to only the fields needed helped on image size
- For the meantime I've moved most data copies to the data preprocessing section of the application (before the TUI starts). I'm about to work on a concept where this preprocessing is pushed to the background an allows the user to navigate to layers that have been loaded.

This is been a pretty big step in the right direction. For instance, the current `amir20/clashleaders:latest` image needs 38 trees built to show all comparisons (^L layer-only comparisons + ^A cumulative comparisons), and has a total of ~820,000 file nodes across all trees. Assuming a FileNode (after optimizations) is about ~400 bytes-ish on average, this means that at least 328 MB of data needs to get generated, not including intermediate data. Pushing all of the tree building (caching) preprocessing up front, this image took 19 seconds to load on my laptop... with the latest optimizations it's down to ~3 seconds! The current work is here: https://github.com/wagoodman/dive/compare/refactor-image-preprocessing...cache-tree-building?expand=1 . I'll make a PR once I fix tests.

After optimizations pprof shows (for CPU time):
```
File: dive
Type: cpu
Time: Dec 4, 2018 at 8:04pm (EST)
Duration: 12.94s, Total samples = 3.70s (28.59%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 1890ms, 51.08% of 3700ms total
Dropped 76 nodes (cum <= 18.50ms)
Showing top 10 nodes out of 137
      flat  flat%   sum%        cum   cum%
     410ms 11.08% 11.08%      780ms 21.08%  runtime.scanobject
     250ms  6.76% 17.84%      250ms  6.76%  cmpbody
     230ms  6.22% 24.05%      350ms  9.46%  runtime.mapaccess1_faststr
     190ms  5.14% 29.19%      210ms  5.68%  runtime.findObject
     180ms  4.86% 34.05%     1750ms 47.30%  github.com/wagoodman/dive/filetree.(*FileNode).VisitDepthChildFirst
     140ms  3.78% 37.84%      170ms  4.59%  runtime.heapBitsSetType
     130ms  3.51% 41.35%      130ms  3.51%  runtime.aeshashbody
     130ms  3.51% 44.86%      470ms 12.70%  sort.(*StringSlice).Less
     120ms  3.24% 48.11%      550ms 14.86%  runtime.mallocgc
     110ms  2.97% 51.08%      130ms  3.51%  runtime.mapiternext
```
and (for memory usage):
```
File: dive
Type: inuse_space
Time: Dec 4, 2018 at 8:02pm (EST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 2MB, 100% of 2MB total
Dropped 1 node (cum <= 0.01MB)
Showing top 10 nodes out of 37
      flat  flat%   sum%        cum   cum%
    1.04MB 52.28% 52.28%     1.04MB 52.28%  github.com/wagoodman/dive/filetree.NewNode
    0.62MB 30.82% 83.10%     1.39MB 69.38%  github.com/wagoodman/dive/filetree.(*FileNode).AddChild
    0.21MB 10.66% 93.76%     0.23MB 11.45%  github.com/wagoodman/dive/filetree.(*FileNode).Path
    0.10MB  4.85% 98.62%     0.37MB 18.57%  github.com/wagoodman/dive/filetree.(*FileNode).Copy
    0.02MB  0.79% 99.41%     0.02MB  0.79%  strings.Replace
    0.01MB  0.59%   100%     0.01MB  0.59%  archive/tar.(*parser).parseString
         0     0%   100%     0.01MB  0.59%  archive/tar.(*Reader).Next
         0     0%   100%     0.01MB  0.59%  archive/tar.(*Reader).next
         0     0%   100%     0.01MB  0.59%  archive/tar.(*Reader).readHeader
         0     0%   100%        2MB   100%  github.com/spf13/cobra.(*Command).Execute
```

To respond to your comments:

1. "Use O(1) datastructures": Initial prototyping showed that prepopulating a hash lookup was taking just as much time as it was to group the tree combinations into one spot... so I instead continued down still using a tree structure. There are some opportunities to store some data structures in a hash (such as the view info as noted in 3, which could be decoupled further). However, I feel that there is more value keeping the tree data structure (instead of replacing it with a hash). One example is comparisons (an important use case highlighted from profiling): when removing a node, what is the best way to remove all child nodes? In a hash data structure it would be a O(n) operation still, since the parent-child relations aren't known. I could imaging a hybrid hash/tree implementation, where pointers to nodes are accessible from a hash (keyed on path), and each node structure has a relation of children... I'm still pondering where it makes sense to implement this.

2. "cache on the visualization layer": I thought about always storing what was drawn to the screen, such that if the user takes that action again, we wouldn't need to create the string again. When I tried it out, dive started using a lot of memory (unsurprisingly). For now I've decided to focus efforts elsewhere, as I feel that this would become more complicated than the benefits implementing it may have. When I originally profiled it appeared that optimizing the filetree string render function was "good enough" (...for now).

3. "decouple UI related structures": Yes! I think that this is a good idea to help performance and would make the code more readable. 

4. "don't redraw everything from scratch, only diffs": though this may be tempting, it will introduce a lot of complexity where profiling doesn't indicate a direct problem. 

5. "cache to disk": I think this is a good idea, limiting how much is cached by purging old cache would need to be quick and automatic.

**Comment by ccinelli** [comment] 2018-12-05 03:15
There is a time vs space tradeoff but here I think that the right data structure and algorithm can save a lot of time and memory. 

Switching layer is still pretty slow for me and it takes 2Gb.
Same test with the new branch:
![profile004](https://user-images.githubusercontent.com/38021940/49486974-4fa40e80-f7f5-11e8-991d-9117940c48c2.png)

Regarding your comments: 

1. I did not mean replacing the tree with a map. I was talking about adding maps where it makes sense.
2. It depends on what you are caching.
3. Only if it is convenient. 
4. It depends how it is implemented.
5. Yes, you can have a LRU mechanism to decide what to deleted when the DB becomes too big. 

I realize that I should be more concrete on describing the  changes that I am thinking about. I will post a little bit more in a little bit. 

You may also want to look at the implementation of https://github.com/cheton/infinite-tree for inspiration.

In general you do not have to visit the whole tree every time there is an update. Anyway, I will write more shortly.

**Comment by ChrisCinelli** [comment] 2018-12-05 09:30
There are a few wastes of CPU and memory at the moment:

1. Visiting an entire large tree is expensive so I would try to limit to when is strictly necessary. 

2. I would *definitely* avoid sorting the `Children`'s keys  *every time* in `VisitDepthChildFirst` like [here](https://github.com/wagoodman/dive/blob/f3f2ec9a8c09ab379e8afe2a9e34efbd04060681/filetree/node.go#L172-L176), [this](https://github.com/wagoodman/dive/blob/f3f2ec9a8c09ab379e8afe2a9e34efbd04060681/filetree/node.go#L212-L216) and in `renderStringTreeBetween` - That is probably why the actual visits are slower than expected. With the current features, the tree can easily order once so it is not necessary doing it every time. 

3. I would keep using a tree (similar to what you already have) but I think it could be more effective if the leaf node was a slice of pointers to `FileInfo` (`nil` if the file was not present on that layer). You can also try a  a `map` where the key is the the `int` is the layer index. The first layer would be in `Data.FileInfo[0]`, the second in `Data.FileInfo[1]` etc. In this way it would be easy to check the files added and removed by looking at `Data.FileInfo[currentLayer - 1]` and `Data.FileInfo[currentLayer + 1]`etc.   It also may make easier to reason about wasted space. You still may have to parse the whole slice to implement #107. 

4. Building complex data structures and let the garbage collection destroy them is quite slow and should be avoided. I would try not to create or destroy trees unless it is REALLY necessary. I do not think you will have to recreate trees or modifying data on it (except the `ViewInfo`). For the folders I would add more data including the `n_tot_files` as  `[] uint` (again one for each layer). I would also capture  in `Data` the `n_tot_visible_files`, the `TotalWastedBytes`, `TotalWastedBytes` and the other "global" metrics. The only time when you may want to modify the tree is if you want to order the nodes in different order. In #110 I suggested letting people order by descending wasted bytes. Alphabetical order and normal file size order also make sense. When you do that you may have to sort the `FileNode.Children`. For that reason I wonder if a `[]*FileNode` instead of a `map[string]*FileNode` for `Children`  may be more effective  And BTW, if you really need it, you can have both and use the map for the `GetNode` and use the slice for order. As far a as I know, it is just easier to re-order a slice in place.

5. Every node of the tree takes a row on the screen.  When you have to render the file tree window you just have to start rendering the row in view. Not only render the string but also you do not have to visit all the nodes and subtree above and below. You can simply scan the tree to find the `start_row` and `end_row` without a full visit when you account of `n_tot_visible_files` in the folders. And, of course you do not have to recalculate the `start_row` every time and you can just keep a pointer to the start FileNode.

6. `Path` in `FileInfo` seems redundant and could be found just following the chain of `Parent`s - It looks like you already have `Node.Path()`

**Comment by wagoodman** [comment] 2018-12-08 18:31
1. Agreed
2. Agreed, I'll update to sort on insert in a follow up PR.
3. I like this idea, and though it may save on space a bit I probably will not incorporate this as it would be a fairly major overhaul without a clear performance advantage.
4. Somewhat agree. The analysis isn't taking up that much time, so including these extra fields and globals I don't think would help all that much --I'm not opposed to it though. Swapping from `map[string]*FileNode` to `[]*FileNode` makes sense given that there are multiple issues asking for ordering by different metrics.
5. Somewhat agree. This is actually fairly fast already, though I think it would be a great idea to keep a pointer to the current top `FileNode` in the filetree pane.
6. Somewhat agree. I think it makes sense to reduce redundancies but I don't think this is the cause of performance degradation and probably isn't taking up an alarming amount of space --I'm not opposed to removing `FileInfo.Path` once memoization is implemented on `FileNode.Path()`.

I'll close this issue as there have been several major performance enhancements (with great results!). Thanks for putting in time to address much of this tech debt. 

I welcome PRs for performance enhancements at anytime!

**Closed** 2018-12-08 18:34 UTC
Labels: In Progress

**Comment by ccinelli** [comment] 2018-12-09 07:16
I think `0.5.0` is a lot faster than before. So it is a great improvement. At the same time, I still have the UI lagging on large images if I scroll down or up on the layer panel. 

I agree on starting on #89. I think that (2) can be kept in mind while implementing it and (4) is actually providing a way to implement different ordering and (2).  You could, in fact, have a `map[string][]*FileNode`. The key is the order type (maybe 'filesize', 'wastesize', 'name', etc) and the value is the slice with the ordered files. Instead of calculating all keys upfront it can be calculated as the user switch ordering mode. You can keep them in the map that act as a cache so you do not have to reorder again later so switching between different ordering modes and back is snappy. One extra feature in (4) is being able to order by "byte wasted" that, in my opinion, is the best order mode to prioritize the work of shrinking the image that is probably the main use case of `dive` (see #110).

I know (3) could be a huge refactoring. It is also true that, the more code is written, the more expensive would be to change that in the future. But I do not blame you if you do not want to jump on it ;-) 
The main advantage of this format is that the information about the same file across layers is co-located. This makes code more readable, improve the access speed and save you from having to copy things between trees. The speed up is not just the analysis (that you do only once), but it is more in avoiding to visit the whole tree in `FileTreeView.Update()` to copy `ViewInfo`.  If you want to further optimize the memory, you can have 2 structures. One for when the file is only on one layer and the one that I described in (3) for when the file changes. 

Regarding (5), at the moment the `visitDeaphChildFirst` is the slowest part. (5) prunes down the part of the tree that needs to be traversed to show the files.

Finally regarding your comment to (6), are not `FileInfo.Path` (specifically `Data.FileInfo.Path`) and `FileNode.Path()` the same? If you want to save memory you just use `Data.FileInfo.Path`. If you want to save CPU you can use `FileNode.Path()` that is what I was suggesting. I am assuming there is a fast way to access the file on the other layers like in (3) but after it is ordered I do not think you need it anymore. So I do not understandwhy `FileNode.Path()` should use memoization. If you are willing to pay the memory toll, why not just use `Data.FileInfo.Path` and get rid of `FileNode.Path()`?
